### PR TITLE
Fix Django 2 compatibility

### PR DESCRIPTION
**Pull request by thomwiggers**
Try to import `reverse` from `django.urls`

### CODE REVIEW

**Comment by romanvm** [comment]
Thanks! However I would ask you to do 2 things: 1) please submit your PR against `develop` branch, 2) please add Django 2 to the Travis CI build matrix to make sure that all test suite is passed.

**Comment by thomwiggers** [comment]
So `filebrowser` appears to be affected by the same problem. I'll see if I can fix it there as well.

**Comment by thomwiggers** [comment]
So `django-filebrowser-no-grappelli` appears to be affected more, I'll work on it later.

**Comment by romanvm** [comment]
Thank anyway. However, even after removing `filebrowser` form the test application I haven't been able to run the test suite locally because of broken access to Django admin that works perfectly in 1.11. Django 2.0 is still in early alpha so I wouldn't rush with it.

**Comment by romanvm** [comment]
I've added a workaround that allows testing in Django 2.0 without `filebrowser`. So now it's save to merge your PR. Thanks!

**Pull request merged**
