### PR TITLE
make example in doc more straightforward

### PR DESCRIPTION
**Pull request by merwok**

### CODE REVIEW

**Comment by romanvm** [comment]
Why have you decided that this is a mistake?

**Comment by merwok** [comment]
`uk` is a country code, not a language code without country code.
https://www.w3.org/International/articles/language-tags/

**Comment by merwok** [comment]
Ha!  I did not think about Ukrainian, I thought this was a typo (`uk` as a country code without language code, but I forgot that code for United Kingdom is `gb`)

**Comment by merwok** [comment]
So there is no typo, but I still offer this PR because I think it’s simpler to understand the examples if they are `en_US` and `en` alone.

**Comment by romanvm** [comment]
The choice of language codes in the example was deliberate and I don't see why they need to be changed.

**Pull request closed without merging**
